steps:
  # Run the Maven build
  - name: gcr.io/elevated-server-275615/hello-service
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-service', '.']

images: ['gcr.io/$PROJECT_ID/hello-service']
