steps:
  # Run the Maven build
  - name: gcr.io/$PROJECT_ID/hello-service
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/hello-serviceROJECT_ID/hello-service', '.']
images: ['gcr.io/$PROJECT_ID/hello-service']
