# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
# Build old tagged images.

  
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/hello-service', '.']
images: ['gcr.io/$PROJECT_ID/hello-service']
