
  
FROM openjdk:8-jdk-alpine as builder

# Copy local code to the container image.
WORKDIR /app
COPY pom.xml ./
COPY src ./src/

# Build a release artifact.
RUN mvn package -DskipTests
COPY --from=builder /app/target/*.jar /helloservice.jar
ENTRYPOINT ["java", "-Djava.security.edg=file:/dev/./urandom","-jar","/helloservice.jar"]
